namespace ZipSpark_New
{
    [default_interface]
    runtimeclass PasswordDialog : Microsoft.UI.Xaml.Controls.ContentDialog
    {
        PasswordDialog();
        PasswordDialog(String archiveName);
        
        String GetPassword();
        Boolean ShouldRememberPassword();
        void ShowError(String message);
    };
}
